RANK_CHOICES = (
  ('lxias', 'ΛΧΙΑΣ'),
  ('epxias', 'ΕΠΧΙΑΣ'),
  ('alxias', 'ΑΛΧΙΑΣ'),
  ('anustis', 'ΑΝΘΣΤΗΣ'),
  ('anulgos', 'ΑΝΘΛΓΟΣ'),
  ('yplgos', 'ΥΠΛΓΟΣ'),
  ('lgos', 'ΛΓΟΣ'),
  ('txis', 'ΤΧΗΣ'),
  ('anxis', 'ΑΝΧΗΣ'),
  ('sxis', 'ΣΧΗΣ'),
  ('tksxos', 'ΤΞΧΟΣ'),
  ('ypstgos', 'ΥΠΣΤΓΟΣ'),
  ('antgos', 'ΑΝΤΓΟΣ'),
  ('stgos', 'ΣΤΓΟΣ'),
)