"""
Django settings for djangochat project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_$0piyib=#^p6=k8c4xvv=mtx)*od!)ew$8xw0x_tvqels%k!w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", "0"))

ALLOWED_HOSTS = ['192.168.56.1', 'localhost', '127.0.0.1','10.0.2.4','0.0.0.0']


LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/rooms'
LOGIN_URL = '/login/'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'channels_redis',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'room',
    'corsheaders',
    'helpdesk_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "https://10.0.2.4", # Replace with your other app's URL
]
ROOT_URLCONF = 'djangochat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangochat.wsgi.application'
ASGI_APPLICATION = 'djangochat.asgi.application'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASE_DIR / 'db.sqlite3'),
#         "TEST": {
#             "NAME": BASE_DIR / "db.sqlite3",
#         },
#     },
#     'external_db': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'dides_helpdesk.prod',
#         'USER': 'POSTGRES_PROD_DIDES_USER',
#         'PASSWORD': 'POSTGRES_PROD_DIDES_PASSWORD',
#         'HOST': '172.18.0.2',  # if the PostgreSQL database is in Docker
#         'PORT': '5432',  # default PostgreSQL port
#         'OPTIONS': {
#             'options': '-c timezone=UTC',
#         }
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dides_helpdesk.prod',
        'USER': 'POSTGRES_PROD_DIDES_USER',
        'PASSWORD': 'POSTGRES_PROD_DIDES_PASSWORD',
        'HOST': 'db',  # if the PostgreSQL database is in Docker
        'PORT': '5432',  # default PostgreSQL port
        'OPTIONS': {
            'options': '-c timezone=UTC',
        },
    }
}
AUTH_USER_MODEL = "helpdesk_app.CustomUser"

# POSTGRESQL
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'djangochat',
#             'USER': 'postgres',
#             'PASSWORD': os.environ.get('DB_PASSWORD'),
#             'HOST': 'localhost',  # Set to the appropriate host
#             'PORT': '',          # Leave empty to use the default PostgreSQL port (5432)
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "djangochat/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"


# User media - here user provided failure/report files will be stored
MEDIA_ROOT = os.path.join(BASE_DIR, "user_files")
MEDIA_URL = '/user_files/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
CSRF_COOKIE_NAME = 'csrftoken_app2'
SESSION_COOKIE_NAME = 'ap2_sessionid'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True
