# Generated by Django 3.1.5 on 2021-04-26 14:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpdesk_app.models
import helpdesk_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα σχηματισμού/μονάδας')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Τοποθεσία')),
                ('is_formation', models.BooleanField(default=False, verbose_name='Σχηματισμός')),
                ('is_major', models.BooleanField(default=False, verbose_name='Μείζων')),
                ('major_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_formation_related_name', to='helpdesk_app.unit', verbose_name='Μείζων σχηματισμός')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_related_name', to='helpdesk_app.unit', verbose_name='Σχηματισμός που υπάγεται')),
            ],
            options={
                'verbose_name': 'Σχηματισμός - Μονάδα',
                'verbose_name_plural': 'Σχηματισμοί - Μονάδες',
            },
        ),
        migrations.CreateModel(
            name='CommunicationMeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Συστήματος')),
            ],
            options={
                'verbose_name': 'Επικοινωνιακό Σύστημα',
                'verbose_name_plural': 'Επικοινωνιακά Συστήματα',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο επικοινωνίας πρέπει να είναι της μορφής 1234567890 με ή χωρίς εθνικό πρόθεμα', regex='^\\+?1?\\d{7,15}$')], verbose_name='Τηλέφωνο επικοινωνίας')),
                ('password_has_changed', models.BooleanField(default=False, verbose_name='Ανανέωση Κωδικού')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk_app.unit', verbose_name='Σχηματισμός - Μονάδα')),
                ('means', models.ManyToManyField(blank=True, to='helpdesk_app.CommunicationMeans', verbose_name='Υπεύθυνος Τηλεπικοινωνιακού Μέσου')),
            ],
            options={
                'verbose_name': 'Χρήστης',
                'verbose_name_plural': 'Χρήστες',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),

        migrations.CreateModel(
            name='BroadbandTransceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('coupling', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ζεύξη')),
                ('coupling_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Κωδικός Ζεύξης')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Μοντέλο')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_broadband', to='helpdesk_app.unit', verbose_name='Σχηματισμός')),
                ('unit_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_from_broadband', to='helpdesk_app.unit', verbose_name='Από')),
                ('unit_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_to_broadband', to='helpdesk_app.unit', verbose_name='Προς')),
            ],
            options={
                'verbose_name': 'Πομποδέκτης Ευρυζωνικού',
                'verbose_name_plural': 'Πομποδέκτες Ευρυζωνικού',
            },
        ),
        migrations.CreateModel(
            name='NetworkSpeed',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Ταχύτητα')),
            ],
            options={
                'verbose_name': 'Ταχύτητα',
                'verbose_name_plural': 'Ταχύτητες',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Όνομα Δρομολόγησης')),
            ],
            options={
                'verbose_name': 'Δρομολόγηση',
                'verbose_name_plural': 'Δρομολογήσεις',
            },
        ),
        migrations.CreateModel(
            name='DigConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Αριθμός')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Σύνδεση')),
                ('formation_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_dig_conn_a', to='helpdesk_app.unit', verbose_name='Σχηματισμός Α')),
                ('unit_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_from', to='helpdesk_app.unit', verbose_name='Μονάδα Α')),
                ('formation_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_dig_conn_b', to='helpdesk_app.unit', verbose_name='Σχηματισμός Β')),
                ('unit_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_to', to='helpdesk_app.unit', verbose_name='Μονάδα Β')),
                ('speed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.networkspeed', verbose_name='Ταχύτητα')),
                ('means', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.communicationmeans', verbose_name='Επικοινωνιακό Σύστημα')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.routing', verbose_name='Δρομολόγηση')),
                ('external', models.BooleanField(default=False, verbose_name='Εξωκείμενη Γραμμή ΕΨΑΔ')),
            ],
            options={
                'verbose_name': 'Ψηφιακό Κύκλωμα',
                'verbose_name_plural': 'Ψηφιακά Κυκλώματα',
            },
        ),
        migrations.CreateModel(
            name='HarpCorrespondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondent', models.CharField(max_length=100, verbose_name='Ανταποκριτής')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='helpdesk_app.unit', verbose_name='Σχηματισμός')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='helpdesk_app.unit', verbose_name='Μονάδα')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Aριθμός Ανταποκριτή')),
                ('device_type', models.CharField(max_length=100, verbose_name='Τύπος Συσκευής')),
                ('is_track_harp', models.BooleanField(default=False, verbose_name='Track Harp')),
            ],
            options={
                'verbose_name': 'Ανταποκριτής Harp',
                'verbose_name_plural': 'Ανταποκριτές Harp',
            },
        ),
        migrations.CreateModel(
            name='PyrseiaServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Όνομα Εξυπηρετητή')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_pyrseia', to='helpdesk_app.unit', verbose_name='Μονάδα')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_pyrseia', to='helpdesk_app.unit', verbose_name='Σχηματισμός')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='Domain')),
                ('exchange', models.CharField(max_length=100, unique=True, verbose_name='Exchange')),
                ('esxi', models.GenericIPAddressField(unique=True, verbose_name='ESXi')),
                ('default_gateway', models.GenericIPAddressField(unique=True, verbose_name='Default Gateway')),
            ],
            options={
                'verbose_name': 'Εξυπηρετητής Πυρσεία',
                'verbose_name_plural': 'Εξυπηρετητές Πυρσεία',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Κόμβου')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_satellite', to='helpdesk_app.unit', verbose_name='Ένταξη σε Δορυφορικό Δίκτυο Σχηματισμού')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_satellite', to='helpdesk_app.unit', verbose_name='Από')),
            ],
            options={
                'verbose_name': 'Δορυφορικός Κόμβος',
                'verbose_name_plural': 'Δορυφορικοί Κόμβοι',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Α/Α')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('status', models.CharField(choices=[('NE', 'ΝΕΑ'), ('OP', 'ΕΚΚΡΕΜΗΣ'), ('PR', 'ΣΕ ΕΞΕΛΙΞΗ'), ('CL', 'ΔΙΕΚΠΕΡΑΙΩΜΕΝΗ')], default='NE', max_length=2, verbose_name='Κατάσταση')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Καταχώρησης')),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Διεκπεραίωσης')),
                ('submitter_rank', models.CharField(choices=[('lxias', 'ΛΧΙΑΣ'), ('epxias', 'ΕΠΧΙΑΣ'), ('alxias', 'ΑΛΧΙΑΣ'), ('anustis', 'ΑΝΘΣΤΗΣ'), ('anulgos', 'ΑΝΘΛΓΟΣ'), ('yplgos', 'ΥΠΛΓΟΣ'), ('lgos', 'ΛΓΟΣ'), ('txis', 'ΤΧΗΣ'), ('anxis', 'ΑΝΧΗΣ'), ('sxis', 'ΣΧΗΣ'), ('tksxos', 'ΤΞΧΟΣ'), ('ypstgos', 'ΥΠΣΤΓΟΣ'), ('antgos', 'ΑΝΤΓΟΣ'), ('stgos', 'ΣΤΓΟΣ')], default='lxias', max_length=10, verbose_name='Βαθμός Καταχωρητή')),
                ('submitter_name', models.CharField(max_length=30, null=True, verbose_name='Όνομα Καταχωρητή')),
                ('solution', models.TextField(blank=True, verbose_name='Επίλυση')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=helpdesk_app.models.Report.upload_location, validators=[helpdesk_app.validators.validate_file_extension], verbose_name='Επισυναπτόμενο Αρχείο')),
                ('primary_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο επικοινωνίας πρέπει να είναι της μορφής 1234567890 με ή χωρίς εθνικό πρόθεμα', regex='^\\+?1?\\d{7,15}$')], verbose_name='Τηλέφωνο επικοινωνίας No.1')),
                ('secondary_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο επικοινωνίας πρέπει να είναι της μορφής 1234567890 με ή χωρίς εθνικό πρόθεμα', regex='^\\+?1?\\d{7,15}$')], verbose_name='Τηλέφωνο επικοινωνίας No.2')),
                ('assigned_dispatcher', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'dispatchers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_user_report', to=settings.AUTH_USER_MODEL, verbose_name='Διεκπεραιωτής Αναφοράς')),
                ('means', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk_app.communicationmeans', verbose_name='Επικοινωνιακό Σύστημα')),
                ('submitter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_user_report', to=settings.AUTH_USER_MODEL, verbose_name='Λογαριασμός Χρήστη Καταχωρητή')),
                ('supervisor_major_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_major_formation_report', to='helpdesk_app.unit', verbose_name='Προϊστάμενος Μείζων Σχηματισμός')),
                ('supervisor_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_unit_report', to='helpdesk_app.unit', verbose_name='Προϊστάμενος Σχηματισμός')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.unit', verbose_name='Κόμβος Αναφοράς')),
            ],
            options={
                'verbose_name': 'Αναφορά',
                'verbose_name_plural': 'Αναφορές',
            },
        ),
        migrations.CreateModel(
            name='HermesNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Αριθμός Κόμβου')),
                ('location', models.CharField(max_length=100, verbose_name='Τοποθεσία')),
                ('node_type', models.CharField(max_length=100, verbose_name='Τύπος Κόμβου')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_hermes_node', to='helpdesk_app.unit', verbose_name='Σχηματισμός')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_hermes_node', to='helpdesk_app.unit', verbose_name='Μονάδα')),
            ],
            options={
                'verbose_name': 'Κόμβος Ερμή',
                'verbose_name_plural': 'Κόμβοι Ερμή',
            },
        ),
        migrations.CreateModel(
            name='HermesConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Αριθμός Ζεύξης')),
                ('node_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node_from', to='helpdesk_app.hermesnode', verbose_name='Από')),
                ('node_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node_to', to='helpdesk_app.hermesnode', verbose_name='Προς')),
            ],
            options={
                'verbose_name': 'Ζεύξη Ερμή',
                'verbose_name_plural': 'Ζεύξεις Ερμή',
            },
        ),
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Βλάβης')),
                ('means', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.communicationmeans', verbose_name='Επικοινωνιακό Σύστημα')),
            ],
            options={
                'verbose_name': 'Τύπος Βλάβης',
                'verbose_name_plural': 'Τύπος Βλάβης',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Α/Α')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('status', models.CharField(choices=[('NE', 'ΝΕΑ'), ('OP', 'ΕΚΚΡΕΜΗΣ'), ('PR', 'ΣΕ ΕΞΕΛΙΞΗ'), ('CL', 'ΔΙΕΚΠΕΡΑΙΩΜΕΝΗ')], default='NE', max_length=2, verbose_name='Κατάσταση')),
                ('date_occurred', models.DateField(blank=True, null=True, verbose_name='Παρουσιάστηκε στις')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Καταχώρησης')),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Διεκπεραίωσης')),
                ('submitter_rank', models.CharField(choices=[('lxias', 'ΛΧΙΑΣ'), ('epxias', 'ΕΠΧΙΑΣ'), ('alxias', 'ΑΛΧΙΑΣ'), ('anustis', 'ΑΝΘΣΤΗΣ'), ('anulgos', 'ΑΝΘΛΓΟΣ'), ('yplgos', 'ΥΠΛΓΟΣ'), ('lgos', 'ΛΓΟΣ'), ('txis', 'ΤΧΗΣ'), ('anxis', 'ΑΝΧΗΣ'), ('sxis', 'ΣΧΗΣ'), ('tksxos', 'ΤΞΧΟΣ'), ('ypstgos', 'ΥΠΣΤΓΟΣ'), ('antgos', 'ΑΝΤΓΟΣ'), ('stgos', 'ΣΤΓΟΣ')], default='lxias', max_length=10, verbose_name='Βαθμός Καταχωρητή')),
                ('submitter_name', models.CharField(max_length=30, null=True, verbose_name='Όνομα Καταχωρητή')),
                ('solution', models.TextField(blank=True, verbose_name='Επίλυση')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=helpdesk_app.models.Failure.upload_location, validators=[helpdesk_app.validators.validate_file_extension], verbose_name='Επισυναπτόμενο Αρχείο')),
                ('primary_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο επικοινωνίας πρέπει να είναι της μορφής 1234567890 με ή χωρίς εθνικό πρόθεμα', regex='^\\+?1?\\d{7,15}$')], verbose_name='Τηλέφωνο επικοινωνίας No.1')),
                ('secondary_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο επικοινωνίας πρέπει να είναι της μορφής 1234567890 με ή χωρίς εθνικό πρόθεμα', regex='^\\+?1?\\d{7,15}$')], verbose_name='Τηλέφωνο επικοινωνίας No.2')),
                ('assigned_dispatcher', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'dispatchers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_user', to=settings.AUTH_USER_MODEL, verbose_name='Διεκπεραιωτής Βλάβης')),
                ('failure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk_app.failuretype', verbose_name='Τύπος Βλάβης')),
                ('means', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk_app.communicationmeans', verbose_name='Επικοινωνιακό Σύστημα')),
                ('related_broadband_transceiver', models.ManyToManyField(blank=True, related_name='related_broadband_transceiver', to='helpdesk_app.BroadbandTransceiver', verbose_name='Πομποδέκτης Ευρυζωνικού')),
                ('related_dig_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_dig_connection', to='helpdesk_app.digconnection', verbose_name='Ψηφιακό Κύκλωμα')),
                ('related_harp_correspondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_harp_correspondent', to='helpdesk_app.harpcorrespondent', verbose_name='Ανταποκριτής Harp')),
                ('related_hermes_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hermes_connection', to='helpdesk_app.hermesconnection', verbose_name='Ζεύξη Ερμή')),
                ('related_hermes_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hermes_node', to='helpdesk_app.hermesnode', verbose_name='Κόμβος Ερμή')),
                ('related_pyrseia_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_pyrseia_server', to='helpdesk_app.pyrseiaserver', verbose_name='Εξυπηρετητής Πυρσεία')),
                ('related_satellite_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_satellite_node', to='helpdesk_app.satellitenode', verbose_name='Δορυφορικός Κόμβος')),
                ('submitter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_user', to=settings.AUTH_USER_MODEL, verbose_name='Λογαριασμός Χρήστη Καταχωρητή')),
                ('supervisor_major_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_major_formation', to='helpdesk_app.unit', verbose_name='Προϊστάμενος Μείζων Σχηματισμός')),
                ('supervisor_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_unit', to='helpdesk_app.unit', verbose_name='Προϊστάμενος Σχηματισμός')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk_app.unit', verbose_name='Επηρεαζόμενος Κόμβος')),
            ],
            options={
                'verbose_name': 'Βλάβη',
                'verbose_name_plural': 'Βλάβες',
            },
        ),
    ]
