# Generated by Django 3.0.2 on 2024-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0005_auto_20241018_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
