# Generated by Django 3.2.25 on 2024-11-04 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0007_auto_20241030_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='last_seen_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk_app.message'),
        ),
    ]
