# Generated by Django 3.2.25 on 2024-11-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0009_roomuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomuser',
            old_name='is_active',
            new_name='is_in_room',
        ),
    ]
