# Generated by Django 3.2.25 on 2024-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0010_rename_is_active_roomuser_is_in_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
