# Generated by Django 3.0.2 on 2024-12-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0012_auto_20241203_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
